### ISSUE TITLE
[Suggestion] 1.19 Please

### ISSUE THREAD

**Issue by TowardtheStars** [lucko/minecraft-command-permissions-fabric#17]
Fabric for Minecraft 1.19 is released, could you plz port this to 1.19?

**Comment by Tetricz** [comment]
bumpin for release 1.19

**Comment by Zeklandia** [comment]
We have been waiting to update our server to 1.19 for over a week now solely because of this mod. It's become a nuisance and interfered with our plans for events. An update would be greatly appreciated.

**Comment by lucko** [comment]
Released - apologies for the delay :)
